application: geo-ds
version: dev
runtime: python
api_version: 1

builtins:
- datastore_admin: on

handlers:

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin
  
- url: /github/.*
  script: app.py

- url: /cells/.*
  script: app.py

- url: /data
  script: app.py
  login: admin

- url: /data/.*
  script: app.py
  login: admin

- url: /data/api.*
  script: app.py
  login: admin
  
- url: /.*
  script: app.py