application: geo-ds
version: dev
runtime: python
api_version: 1

inbound_services:
- mail

builtins:
- datastore_admin: on
- appstats: on

handlers:

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

# GitHub service hooks
- url: /service-hooks/post-receive
  script: github_service_hooks.py 

- url: /_ah/mail/.+ 
  script: inbound_mail_handler.py
  login: admin

- url: /api/.*
  script: api.py
  
- url: /github/.*
  script: app.py

- url: /cells/.*
  script: app.py

- url: /admin/.*
  script: app.py
  login: admin

- url: /.*
  script: api.py