# Test configuration for bulkloading Bio1 Cell and CellIndex entities.

python_preamble:
- import: base64
- import: re
- import: google.appengine.ext.bulkload.transform
- import: google.appengine.ext.bulkload.bulkloader_wizard
- import: google.appengine.ext.db
- import: google.appengine.api.datastore
- import: google.appengine.api.users
- import: helper

transformers:

- kind: Cell
  connector: csv
  connector_options:
    encoding: utf_8

  property_map:
    - property: __key__
      external_name: CellKey
      import_transform: transform.create_foreign_key('Cell')

    - property: r
      external_name: RID
      import_transform: transform.none_if_empty(str)

- kind: CellIndex
  connector: csv
  connector_options:
    encoding: utf_8
  
  property_map:
    - property: __key__
      external_name: CellKey
      import_transform: helper.create_key() 

    - property: n
      external_name: varname
      import_transform: helper.get_varname()

    - property: v
      external_name: avg_Band1
      import_transform: helper.get_varval()

    - property: x #within_x
      external_name: avg_Band1
      import_transform: helper.within_list(1)

    - property: y #within_y
      external_name: avg_Band1
      import_transform: helper.within_list(5)

    - property: z #within_z
      external_name: avg_Band1
      import_transform: helper.within_list(10)

  #post_import_function: helper.add_dynamic_properties