# Test configuration for bulkloading Bio1 Cell and CellIndex entities.

python_preamble:
- import: base64
- import: re
- import: google.appengine.ext.bulkload.transform
- import: google.appengine.ext.bulkload.bulkloader_wizard
- import: google.appengine.ext.db
- import: google.appengine.api.datastore
- import: google.appengine.api.users
- import: helper

transformers:

- kind: Cell
  connector: csv
  connector_options:
    encoding: utf_8
  
  property_map:
    - property: __key__
      external_name: key
      export_transform: datastore.Key.name

    - property: bio1
      external_name: json
      import_transform: helper.to_json()      
      
- kind: CellIndex
  connector: csv
  connector_options:
    encoding: utf_8
  
  property_map:
    - property: __key__
      import_template: "%(key)s_%(variable)s"
      import_transform: helper.create_key()
                            
    - property: value
      external_name: value
      import_transform: transform.none_if_empty(int)

    - property: scaledvalue
      external_name: scaledvalue
      import_transform: transform.none_if_empty(int)

    - property: variable
      external_name: variable
      import_transform: transform.none_if_empty(str)

    - property: within_1
      import_template: "%(scaledvalue)s"
      import_transform: helper.within_list(1)

    - property: within_2
      import_template: "%(scaledvalue)s"
      import_transform: helper.within_list(2)

    - property: within_3
      import_template: "%(scaledvalue)s"
      import_transform: helper.within_list(3)

    - property: within_4
      import_template: "%(scaledvalue)s"
      import_transform: helper.within_list(4)
      
    - property: within_5
      import_template: "%(scaledvalue)s"
      import_transform: helper.within_list(5)

    - property: within_10
      import_template: "%(scaledvalue)s"
      import_transform: helper.within_list(10)
