python_preamble:
- import: base64
- import: re
- import: google.appengine.ext.bulkload.transform
- import: google.appengine.ext.bulkload.bulkloader_wizard
- import: google.appengine.ext.db
- import: google.appengine.api.datastore
- import: google.appengine.api.users

transformers:

- kind: Variable
  connector: csv
  connector_options:
    encoding: utf_8
  
  property_map:
    - property: __key__
      external_name: key
      export_transform: datastore.Key.name

    - property: database
      external_name: database
      import_transform: transform.none_if_empty(str)

    - property: version
      external_name: version
      import_transform: transform.none_if_empty(str)

    - property: release
      external_name: release
      import_transform: transform.none_if_empty(int)
      
    - property: created
      external_name: created
      import_transform: transform.import_date_time('%Y%m%d')
      
    - property: projection
      external_name: projection
      import_transform: transform.none_if_empty(str)

    - property: datum
      external_name: datum
      import_transform: transform.none_if_empty(str)

    - property: minval
      external_name: minval
      import_transform: transform.none_if_empty(int)
      
    - property: maxval
      external_name: maxval
      import_transform: transform.none_if_empty(int)
      
    - property: name
      external_name: name
      import_transform: transform.none_if_empty(str)